name: Validate

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  phpcs:
    name: WordPress Coding Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coding_standard: none
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run PHPCS
        run: composer run-script lint
